alias c=cd
alias cl=clear
alias b=exit
alias v=nvim
alias g=git
alias gst="git status"
alias gca="git add . && git commit -m"
alias gpsh="git push"
alias gpl="git pull"
alias la="ls -la"
alias k="kubectl"
alias kg="kubectl get"
alias kd="kubectl describe"
